[package]
name = "dotfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
